server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.128.130:10068/tensquare_base?characterEncoding=utf-8
    username: root
    password: Ttxs0315!
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
  rabbitmq:
    host: 192.168.128.130
eureka:
  client:
    service-url:
      defaultZone: http://192.168.128.130:6868/eureka/
  instance:
    prefer-ip-address: true
